[package]
authors = ["Richard Cook", "Dan Reeves"]
description = "Absolute paths"
homepage = "https://github.com/rcook/joat-path-rs/"
license = "MIT"
name = "joat-path"
version = "0.0.7"
edition = "2021"

[dependencies]
